theme: jekyll-theme-minimal

title: Auth Template Documentation
description: A secure full-stack authentication template using Next.js and NestJS
show_downloads: false
baseurl: '/auth-template'
url: 'https://ogghst.github.io'

github:
  repository_url: https://ogghst.github.io/auth-template

header_pages:
  - index.md
  - guide/getting-started.md
  - guide/introduction.md
  - api/index.md
  - auth/flow.md
