remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: Auth Template
description: This project is a secure full-stack application template that demonstrates modern authentication practices using GitHub OAuth. Built with Next.js 14 and NestJS 10, it provides a robust foundation for developing secure web applications.
