remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: Auth Template Documentation
description: A secure full-stack authentication template using Next.js and NestJS
show_downloads: false

github:
  repository_url: https://github.com/ogghst/auth-template
